{"name": "test login4", "status": "passed", "description": "тест проверяет, что при введении неверных данных отображается ошибка", "steps": [{"name": "open browser", "status": "passed", "start": 1713584067680, "stop": 1713584084962}, {"name": "get text", "status": "passed", "parameters": [{"name": "locator", "value": "('css selector', 'h3[data-test=\"error\"]')"}], "start": 1713584085153, "stop": 1713584085181}], "attachments": [{"name": "log", "source": "87c2d8c6-3773-4e17-87c3-8ffb41fc9b93-attachment.txt", "type": "text/plain"}], "start": 1713584067680, "stop": 1713584085181, "uuid": "26ad73b6-2e39-4e01-96c5-237c709de85f", "historyId": "914ad09e2b30d6d95189061c225a031b", "testCaseId": "914ad09e2b30d6d95189061c225a031b", "fullName": "tests.test_login.TestLogin#test_login_wrong_credentials", "labels": [{"name": "severity", "value": "critical"}, {"name": "epic", "value": "Testing login"}, {"name": "tag", "value": "negative"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-NVI1VI2"}, {"name": "thread", "value": "22940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_login"}]}